import "./ReportTemplate.css";

function ReportTemplate({
  detections,
  originalImage,
  detectedImage,
}) {
  const totalDefects = detections.length;

  const avgConfidence =
    totalDefects === 0
      ? 0
      : (
          detections.reduce(
            (sum, d) => sum + d.confidence,
            0
          ) / totalDefects
        ) * 100;

  const high = detections.filter(
    (d) => d.severity === "High"
  ).length;

  const medium = detections.filter(
    (d) => d.severity === "Medium"
  ).length;

  const low = detections.filter(
    (d) => d.severity === "Low"
  ).length;

  return (
    <div id="pdf-report" className="report">

      <h1>AI PCB DEFECT INSPECTION REPORT</h1>

      <hr />

      <div className="details">
        <p><strong>Date:</strong> {new Date().toLocaleDateString()}</p>
        <p><strong>Time:</strong> {new Date().toLocaleTimeString()}</p>
      </div>

      <h2>PCB Images</h2>

      <div className="image-section">

        <div>
          <h3>Original PCB</h3>

          <img
            src={originalImage}
            alt="Original"
          />
        </div>

        <div>
          <h3>Detected PCB</h3>

          <img
            src={detectedImage}
            alt="Detected"
          />
        </div>

      </div>

      <h2>Inspection Summary</h2>

      <table className="summary-table">
        <tbody>

          <tr>
            <td>Total Defects</td>
            <td>{totalDefects}</td>
          </tr>

          <tr>
            <td>Average Confidence</td>
            <td>{avgConfidence.toFixed(2)}%</td>
          </tr>

          <tr>
            <td>High Severity</td>
            <td>{high}</td>
          </tr>

          <tr>
            <td>Medium Severity</td>
            <td>{medium}</td>
          </tr>

          <tr>
            <td>Low Severity</td>
            <td>{low}</td>
          </tr>

        </tbody>
      </table>

      <h2>Detected Defects</h2>

      <table className="defect-table">

        <thead>

          <tr>
            <th>Defect</th>
            <th>Severity</th>
            <th>Confidence</th>
          </tr>

        </thead>

        <tbody>

          {detections.map((defect, index) => (

            <tr key={index}>

              <td>{defect.name}</td>

              <td>{defect.severity}</td>

              <td>
                {(defect.confidence * 100).toFixed(2)}%
              </td>

            </tr>

          ))}

        </tbody>

      </table>

      <h2>Repair Recommendations</h2>

      {detections.map((defect, index) => (

        <div key={index} className="recommendation">

          <strong>{defect.name}</strong>

          <p>{defect.repair_recommendation}</p>

        </div>

      ))}

      <hr />

      <p className="footer">
        Generated by AI Powered PCB Defect Detection & Repair Recommendation System
      </p>

    </div>
  );
}

export default ReportTemplate;