from ultralytics import YOLO
from app.recommendations.repair_engine import get_repair_recommendation
from pathlib import Path

MODEL_PATH = Path(__file__).resolve().parent.parent / "models" / "best.pt"
model = None 


def load_model():
    global model

    if model is None:
        model = YOLO(str(MODEL_PATH)) # load the model from the specified path i.e "models/best.pt"

    return model


def detect(image_path):
    model = load_model()

    results = model.predict( # runs YOLOv8 inference on the input image and returns the results
        source=image_path, #input image path
        save=True, # automatically saved the annotated image in the "runs/detect" directory
        conf=0.5 #Confidence threshold.Only detections above 50% are kept 
    )

    detections = [] # empty list that will store the detection results

    result = results[0]

    for box in result.boxes:
        class_id = int(box.cls[0]) # yolo predicts the class of the detected object as an integer index. This line retrieves the class index of the detected object from the box object and converts it to an integer.
        class_name = result.names[class_id] #Convert the class index to the corresponding class name using the names attribute of the result object. This line retrieves the human-readable class name of the detected object based on its class index.
        confidence = float(box.conf[0]) # retrieves the confidence score of the detection and converts it to a float.

        x1, y1, x2, y2 = map(float, box.xyxy[0]) # retrieves the bounding box coordinates and converts them to floats.

        repair_info = get_repair_recommendation(class_name) # gets the repair recommendation for the detected defect class using the get_repair_recommendation function.

        detections.append({ #Every time YOLO detects a defect, we store all its information in this list.
            "defect_code": class_name, #Stores the class predicted by YOLO.
            "confidence": round(confidence, 3), #Rounds the confidence score to 3 decimal places.
            "bbox": [ #These four values tell us where the defect is located in the image.
                round(x1, 2), #bounding box coordinates.
                round(y1, 2),
                round(x2, 2),
                round(y2, 2)
            ],
            #These are sent to the frontend so they can be shown to the user.
            "name": repair_info["name"],
            "severity": repair_info["severity"],
            "description": repair_info["description"],
            "possible_causes": repair_info["possible_causes"],
            "repair_recommendation": repair_info["repair_recommendation"],
            "inspection_tips": repair_info["inspection_tips"]
        })

    output_dir = Path(result.save_dir)

    image_files = list(output_dir.glob("*.jpg")) + list(output_dir.glob("*.jpeg")) + list(output_dir.glob("*.png"))

    annotated_image = max(image_files, key=lambda f: f.stat().st_mtime) #picks the most recently created image.

    relative_path = annotated_image.relative_to(Path("runs").resolve())

    return { #this sends the detection results and the path to the annotated image back to the frontend
        "detections": detections,
        "annotated_image": f"/static/{relative_path.as_posix()}"
    }



"""
PCB Defect Detection Module

This file is responsible for performing PCB defect detection using the
trained YOLO11 model.

Workflow:
1. Loads the trained YOLO11 model (best.pt) into memory.
2. Receives the uploaded PCB image from the Upload API.
3. Runs object detection on the image using the YOLO model.
4. Extracts the detected defect information, including:
   - Defect class
   - Confidence score
   - Bounding box coordinates
5. Retrieves additional information for each detected defect from
   repair_engine.py, such as:
   - Defect name
   - Severity
   - Description
   - Possible causes
   - Repair recommendations
   - Inspection tips
6. Retrieves the annotated PCB image generated by YOLO.
7. Returns the detection results and annotated image path to the Upload API.

The Upload API then sends this information to the React frontend, where
the original image, detected image, defect details, repair recommendations,
summary statistics, and PDF report are displayed.
"""